name: Quarkus CI

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  quarkus-ci:
    # Name the Job
    name: Quarkus CI
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 11
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Compile
      - name: Compile with Maven
        run: mvn --batch-mode --update-snapshots compile

      # Test
      - name: Test with Maven
        run: mvn --batch-mode --update-snapshots test

      # Build
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify